import './globals.css'
import { Poppins } from 'next/font/google'

const inter = Poppins({ 
  weight:"500",
  subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark:bg-gray-900'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
